export const COMMISSARIATS_TYPES = {
  LOAD_COMMISSARIAT: 'COMMISSARIAT_TYPES.LOAD_COMMISSARIATS',
  CREATE_COMMISSARIAT: 'COMMISSARIAT_TYPES.CREATE_COMMISSARIAT',
  EDIT_COMMISSARIAT: 'COMMISSARIAT_TYPES.EDIT_COMMISSARIAT',
  DELETE_COMMISSARIAT: 'COMMISSARIAT_TYPES.DELETE_COMMISSARIAT',
}