export const COMMUNITIES_TYPES = {
  LOAD_COMMUNITIES: 'COMMUNITIES_TYPES.LOAD_COMMUNITIES',
  CREATE_COMMUNITY: 'COMMUNITIES_TYPES.CREATE_COMMUNITY',
  EDIT_COMMUNITY: 'COMMUNITIES_TYPES.EDIT_COMMUNITY',
  DELETE_COMMUNITY: 'COMMUNITIES_TYPES.DELETE_COMMUNITY',
}