export const CUSTOMERS_TYPES = {
  LOAD_CUSTOMERS: 'CUSTOMERS_TYPES.LOAD_CUSTOMERS',
  CREATE_CUSTOMER: 'CUSTOMERS_TYPES.CREATE_CUSTOMER',
  EDIT_CUSTOMER: 'CUSTOMERS_TYPES.EDIT_CUSTOMER',
  DELETE_CUSTOMER: 'CUSTOMERS_TYPES.DELETE_CUSTOMER',
}