export const EXPENSES_TYPES = {
  LOAD_EXPENSES: 'EXPENSES_TYPES.LOAD_EXPENSES',
  CREATE_EXPENSE: 'EXPENSES_TYPES.CREATE_EXPENSE',
  EDIT_EXPENSE: 'EXPENSES_TYPES.EDIT_EXPENSE',
  DELETE_EXPENSE: 'EXPENSES_TYPES.DELETE_EXPENSE',
}