export const GROUPS_TYPES = {
  LOAD_GROUPS: 'GROUPS_TYPES.LOAD_GROUP',
  CREATE_GROUP: 'GROUPS_TYPES.CREATE_GROUP',
  EDIT_GROUP: 'GROUPS_TYPES.EDIT_GROUP',
  DELETE_GROUP: 'GROUPS_TYPES.DELETE_GROUP',
}