export const HEALTH_STATUSES_TYPES = {
  LOAD_HEALTH_STATUSES: 'HEALTH_STATUSES_TYPES.LOAD_HEALTH_STATUSES',
  CREATE_HEALTH_STATUS: 'HEALTH_STATUSES_TYPES.CREATE_HEALTH_STATUS',
  EDIT_HEALTH_STATUS: 'HEALTH_STATUSES_TYPES.EDIT_HEALTH_STATUS',
  DELETE_HEALTH_STATUS: 'HEALTH_STATUSES_TYPES.DELETE_HEALTH_STATUS',
}