export const INVESTORS_TYPES = {
  LOAD_INVESTORS: 'INVESTORS_TYPES.LOAD_INVESTORS',
  CREATE_INVESTOR: 'INVESTORS_TYPES.CREATE_INVESTOR',
  EDIT_INVESTOR: 'INVESTORS_TYPES.EDIT_INVESTOR',
  DELETE_INVESTOR: 'INVESTORS_TYPES.DELETE_INVESTOR',
}