export const INVESTMENTS_TYPES = {
  LOAD_INVESTMENTS: 'INVESTMENTS_TYPES.LOAD_INVESTMENTS',
  CREATE_INVESTMENT: 'INVESTMENTS_TYPES.CREATE_INVESTMENT',
  EDIT_INVESTMENT: 'INVESTMENTS_TYPES.EDIT_INVESTMENT',
  DELETE_INVESTMENT: 'INVESTMENTS_TYPES.DELETE_INVESTMENT',
}