export const NATIONALITIES_TYPES = {
  LOAD_NATIONALITIES: 'NATIONALITIES_TYPES.LOAD_NATIONALITIES',
  CREATE_NATIONALITIES: 'NATIONALITIES_TYPES.CREATE_NATIONALITIES',
  EDIT_NATIONALITIES: 'NATIONALITIES_TYPES.EDIT_NATIONALITIES',
  DELETE_NATIONALITIES: 'NATIONALITIES_TYPES.DELETE_NATIONALITIES',
}