export const PRIVILEGES_TYPES = {
  LOAD_PRIVILEGES: 'PRIVILEGES_TYPES.LOAD_PRIVILEGES',
  CREATE_PRIVILEGE: 'PRIVILEGES_TYPES.CREATE_PRIVILEGE',
  EDIT_PRIVILEGE: 'PRIVILEGES_TYPES.EDIT_PRIVILEGE',
  DELETE_PRIVILEGE: 'PRIVILEGES_TYPES.DELETE_PRIVILEGE',
}