export const PRODUCTS_TYPES = {
  LOAD_PRODUCTS: 'PRODUCTS_TYPES.LOAD_PRODUCTS',
  CREATE_PRODUCT: 'PRODUCTS_TYPES.CREATE_PRODUCT',
  EDIT_PRODUCT: 'PRODUCTS_TYPES.EDIT_PRODUCT',
  DELETE_PRODUCT: 'PRODUCTS_TYPES.DELETE_PRODUCT',
}