export const PROFESSIONS_TYPES = {
  LOAD_PROFESSIONS: 'PROFESSIONS_TYPES.LOAD_PROFESSIONS',
  CREATE_PROFESSION: 'PROFESSIONS_TYPES.CREATE_PROFESSION',
  EDIT_PROFESSION: 'PROFESSIONS_TYPES.EDIT_PROFESSION',
  DELETE_PROFESSION: 'PROFESSIONS_TYPES.DELETE_PROFESSION',
  LOAD_PROFESSION_SUBJECTS: 'PROFESSIONS_TYEPS.LOAD_PROFESSION_SUBJECTS',
  CREATE_SUBJECT: 'PROFESSION_TYPES.CREATE_SUBJECT',
  EDIT_SUBJECT: 'PROFESSION_TYPES.EDIT_SUBJECT',
  DELETE_SUBJECT: 'PROFESSION_TYPES.DELETE_SUBJECT'
}