export const REGIONS_TYPES = {
  LOAD_REGIONS: 'REGIONS_STATUSES.LOAD_REGIONS',
  CREATE_REGION: 'REGIONS_STATUSES.CREATE_REGION',
  EDIT_REGION: 'REGIONS_STATUSES.EDIT_REGION',
  DELETE_REGION: 'REGIONS_STATUSES.DELETE_REGION',
}