export const STUDENTS_TYPES = {
  LOAD_STUDENTS: 'STUDENTS_TYPES.LOAD_STUDENTS',
  CREATE_STUDENT: 'STUDENTS_TYPES.CREATE_STUDENTS',
  EDIT_STUDENT: 'STUDENTS_TYPES.EDIT_STUDENTS',
  DELETE_STUDENTS: 'STUDENTS_TYPES.DELETE_STUDENTS',
}