export const TARGETS_TYPES = {
	LOAD_TARGETS: 'TARGETS_TYPES.LOAD_TARGETS',
	CREATE_TARGET: 'TARGETS_TYPES.CREATE_TARGET',
	EDIT_TARGET: 'TARGETS_TYPES.EDIT_TARGET',
	DELETE_TARGET: 'TARGETS_TYPES.DELETE_TARGET',
};
