export const TREATMENTS_TYPES = {
  LOAD_TREATMENTS: 'TREATMENTS_TYPES.LOAD_PRODUCTS',
  CREATE_TREATMENT: 'TREATMENTS_TYPES.CREATE_TREATMENT',
  EDIT_TREATMENT: 'TREATMENTS_TYPES.EDIT_TREATMENT',
  DELETE_TREATMENT: 'TREATMENTS_TYPES.DELETE_TREATMENT',
}